-- MySQL Script generated by MySQL Workbench
-- Mon Jan 17 11:30:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bi30tloqqg6aqnsjzk5h
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bi30tloqqg6aqnsjzk5h
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bi30tloqqg6aqnsjzk5h` DEFAULT CHARACTER SET utf8 ;
USE `bi30tloqqg6aqnsjzk5h` ;

-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`add_on`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`add_on` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`restaurant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `idx_name` (`name`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`dish` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `cuisine` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `min_addon` INT NOT NULL,
  `max_addon` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dish_restaurant1_idx` (`restaurant_id` ASC) VISIBLE,
  FULLTEXT INDEX `idx_name` (`name`) VISIBLE,
  FULLTEXT INDEX `idx_description` (`description`) VISIBLE,
  CONSTRAINT `fk_dish_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`restaurant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`add_on_dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`add_on_dish` (
  `add_on_id` INT NOT NULL,
  `dish_id` INT NOT NULL,
  PRIMARY KEY (`add_on_id`, `dish_id`),
  INDEX `fk_add_on_has_dish_dish1_idx` (`dish_id` ASC) VISIBLE,
  INDEX `fk_add_on_has_dish_add_on1_idx` (`add_on_id` ASC) VISIBLE,
  CONSTRAINT `fk_add_on_has_dish_add_on1`
    FOREIGN KEY (`add_on_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`add_on` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_add_on_has_dish_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`dish` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`category_dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`category_dish` (
  `categories_id` INT NOT NULL,
  `dish_id` INT NOT NULL,
  PRIMARY KEY (`categories_id`, `dish_id`),
  INDEX `fk_categories_has_dish_dish1_idx` (`dish_id` ASC) VISIBLE,
  INDEX `fk_categories_has_dish_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_has_dish_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_categories_has_dish_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`dish` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`fav`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`fav` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fav_restaurant1_idx` (`restaurant_id` ASC) VISIBLE,
  INDEX `fk_fav_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_fav_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`restaurant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fav_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`order_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `user_id` INT NOT NULL,
  `dish_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_item_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_order_item_dish1_idx` (`dish_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`dish` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_item_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`order_item_add_on`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`order_item_add_on` (
  `order_item_id` INT NOT NULL,
  `add_on_id` INT NOT NULL,
  PRIMARY KEY (`order_item_id`, `add_on_id`),
  INDEX `fk_order_item_has_add_on_add_on1_idx` (`add_on_id` ASC) VISIBLE,
  INDEX `fk_order_item_has_add_on_order_item1_idx` (`order_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_has_add_on_add_on1`
    FOREIGN KEY (`add_on_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`add_on` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_item_has_add_on_order_item1`
    FOREIGN KEY (`order_item_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`order_item` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`promoted_res`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`promoted_res` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `promoted_res_id_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `promoted_res_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`restaurant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bi30tloqqg6aqnsjzk5h`.`restaurant_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bi30tloqqg6aqnsjzk5h`.`restaurant_categories` (
  `restaurant_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`restaurant_id`, `categories_id`),
  INDEX `fk_restaurant_has_categories_categories1_idx` (`categories_id` ASC) VISIBLE,
  INDEX `fk_restaurant_has_categories_restaurant_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_restaurant_has_categories_restaurant`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `bi30tloqqg6aqnsjzk5h`.`restaurant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;