// Generated by https://quicktype.io

export interface CartResponse {
    success: boolean;
    data: CartItem[];
}

export interface CartItem {
    order_id: number;
    id: number;
    quantity: number;
    user_id: number;
    dish_id: number;
    name: string;
    description: string;
    cuisine: string;
    price: number;
    min_addon: number;
    max_addon: number;
    restaurant_id: number;
    image_url: string;
    cat: string;
    addons: Addon[];
}

export interface AddonResponse {
    success: boolean;
    data: Addon[];
}

export interface Addon {
    id: number;
    name: string;
    price: number;
    url: string;
}
