// Generated by https://quicktype.io

export type RestaurantResponse = {
    success: boolean;
    data: Restaurant[];
};

export interface Restaurant {
    id: number;
    name: string;
    description: string;
    image_url: string;
}
